language: cpp
compiler: gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf-archive libboost-all-dev xsltproc
  - ./bootstrap
  - ./configure
script: make
branches:
  only: master
