language: cpp
compiler: g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev
    - libxslt1.1
    - python-lxml
    - doxygen

before_script:
  - lsb_release -a
  - uname -a
  - sudo apt-add-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted"
  - sudo add-apt-repository -y "deb http://ppa.launchpad.net/dns/gnu/ubuntu precise main"
  - sudo add-apt-repository -y "deb http://ppa.launchpad.net/wnoronha/thrift/ubuntu precise main"
  - sudo add-apt-repository -y "deb http://ppa.launchpad.net/kzemek/boost/ubuntu utopic main"
  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
  - # sudo apt-get install python-software-properties 
  - # sudo apt-add-repository -y ppa:libreoffice/libreoffice-4-2
  - sudo apt-get update -qq
  - sudo apt-get install cmake-data cmake
  - # sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - # sudo apt-get install -qq g++-4.9
  - sudo apt-get install -qq automake autoconf autoconf-archive
  - # dpkg -S /usr/include/boost/version.hpp
  - grep BOOST_LIB_VERSION /usr/include/boost/version.hpp
  - sudo apt-get install -qq libthrift-dev libthrift0 thrift-compiler
  - # sudo apt-get install -qq libxslt1.1 python-lxml libthrift-dev libthrift0 thrift-compiler
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - echo "DIR:BUILD=/tmp/${USER}/utxx"               > .cmake-args.$(hostname)
  - echo "DIR:INSTALL=/opt/pkg/@PROJECT@/@VERSION@" >> .cmake-args.$(hostname)
  - echo "PKG_ROOT_DIR=/usr/local"                  >> .cmake-args.$(hostname)
  - echo "WITH_THRIFT=ON"                           >> .cmake-args.$(hostname)
  - echo "BOOST_ROOT=/usr/local/boost"              >> .cmake-args.$(hostname)
  - echo "WITH_ENUM_SERIALIZATION=ON"               >> .cmake-args.$(hostname)
  - g++ --version
script:
  - make bootstrap generator=make build=Debug
  - make
after_script:
  - # cat config.log
branches:
  only: master
