language: cpp
compiler: gcc
before_script:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ raring main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxslt1.1 xsltproc autoconf-archive libboost-all-dev
  - ./bootstrap
  - ./configure
script: make debug=true optimize=3
branches:
  only: master
