language: cpp
compiler: gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq xsltproc
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ raring main universe"
  - sudo apt-get install -qq autoconf-archive libboost-all-dev
  - ./bootstrap
  - ./configure
script: make -j $(grep MHz /proc/cpuinfo | wc -l) debug=true optimize=3
branches:
  only: master
