language: cpp
compiler: gcc
before_script:
  - sudo apt-add-repository --yes ppa:wheezy/boost # boost 1.49 (in future 1.55)
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf-archive libboost-all-dev xsltproc
  - ./bootstrap
  - ./configure
script: make
branches:
  only: master
